### ISSUE TITLE
Error/Issue

### ISSUE THREAD

**Issue by KalixTk** [SrMilton/AutoRank2-CSGO#2]
username password    **(Edited the username and password)**
Open Steam, starting process ...
Starting CS:GO

_Get this error when building could be why just have no ideo how to fix it_
`'hProcess' could be '0':  this does not adhere to the specification for the function 'CloseHandle'.`

**Just stays like this after opening the executable**

**Comment by SrMilton** [comment]
Do you know wich line is this?
